DROP TABLE IF EXISTS SEARCH;
DROP TABLE IF EXISTS RESULT;

CREATE TABLE SEARCH(
 ID INTEGER PRIMARY KEY AUTOINCREMENT,
 DATA_TO_MATCH varchar(4000) NOT NULL,
 HTML_LEARNING_DATA varchar(999999) NOT NULL, -- A bit of overprovisionning here? :P
 URL varchar(4000) NOT NULL,
 NAME varchar(100) NOT NULL,
 PATTERN varchar(4000) NOT NULL,
 CRAWL_LIMIT UNSIGNED INTEGER NOT NULL DEFAULT 0
 DATA_CLEANING varchar(4000) NOT NULL,
 CLEANING_GUID varchar(100) NOT NULL
);

CREATE TABLE RESULT(
 ID INTEGER PRIMARY KEY AUTOINCREMENT,
 SEARCH_ID INTEGER,
 PAGE varchar(100),
 SCORE INTEGER,
 TIMESTAMP DATETIME,
 FOREIGN KEY(SEARCH_ID) REFERENCES SEARCH(ID) ON DELETE CASCADE
);
